name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for WIF

    concurrency:
      group: backend-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image
        run: |
          IMG=${{ secrets.DOCKER_USERNAME }}/backend-app
          docker build -t $IMG:latest -t $IMG:${{ github.sha }} .
          docker push $IMG:latest
          docker push $IMG:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image=docker.io/${{ secrets.DOCKER_USERNAME }}/backend-app:${{ github.sha }} \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
